# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5ce14f8c49b122ee4d2b6015ec62783a1e4943350ef9f1d54ecf666d3b79c00547fd284786e4435dde2ba3ef8a1cdbd319ff68b00c81773978ae3b6d9e01e73

test:
  secret_key_base: 996308fcae5aed069628a936db8f678c15b5d2988747e7c72b006ed2400815d6637eeb6382a62cbdc94a4f0677e175c23391a17395276e88be58dfcc469dbf2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
